### ISSUE TITLE
which dotnet version

### ISSUE THREAD

**Issue by mmiat** [borisbabic/hearthstone_hdt_linux#1]
there is a dotnet version better of others? 4.5, 4.5.2, 4.6, 4.7?
thanks

**Comment by borisbabic** [comment]
The only thing I _know_ works is what is in the [readme](https://github.com/borisbabic/hearthstone_hdt_linux/blob/1ffbaaa8da0eb962d6cc4a61ae7bf295ba45e620/README.md). Others may work but I'm satisfied with what is in the [readme](https://github.com/borisbabic/hearthstone_hdt_linux/blob/1ffbaaa8da0eb962d6cc4a61ae7bf295ba45e620/README.md). If you do try with one of the rest please share whether it was a success or not.

**Comment by mmiat** [comment]
i tried to install dotnet472, dotnet471, dotnet47 and dotnet462, none of them works
when i tried to install dotnet462, it installed also dotnet46, dotnet45 and dotnet40
