### ISSUE TITLE
can't see image that last opponent warband in battlegrounds.

### ISSUE THREAD

**Issue by mereong269** [borisbabic/hearthstone_hdt_linux#13]
i'm not good at English.

HDT can't create jpg image file that last opponent warband to play battlegrounds on Ubuntu.

i have a temporary solution for this.   just for battlegrounds.

last update : 20.2
-----------------------------------------------------------------------------------------------------------------------------------------------

download attached file and then extract below.

~/.wine.heartstone/drive_c/users/$USER/Application Data/HearthstoneDeckTracker/Images/CardPortraits/

[CardPortraits.tar.gz](https://github.com/borisbabic/hearthstone_hdt_linux/files/6424474/CardPortraits.tar.gz)

-----------------------------------------------------------------------------------------------------------------------------------------------

**Comment by D33M0N** [comment]
for some reason firefox thinks this file contains virus...

**Comment by mereong269** [comment]
i don't know why but upload image file again ...

[ConvertImage.tar.gz](https://github.com/borisbabic/hearthstone_hdt_linux/files/5792960/ConvertImage.tar.gz)

**Comment by mereong269** [comment]
update image ...    + argent braggart 
[ConvertImage.tar.gz](https://github.com/borisbabic/hearthstone_hdt_linux/files/5826892/ConvertImage.tar.gz)

**Comment by mereong269** [comment]
update image for  patch 19.4  + ( soul devourer, ring matron )

[ConvertImage.tar.gz](https://github.com/borisbabic/hearthstone_hdt_linux/files/5852133/ConvertImage.tar.gz)

**Comment by mereong269** [comment]
update 20.04

download and extract tar file to below directory.

"~/.wine.heartstone/drive_c/users/$USER/Application Data/HearthstoneDeckTracker/Images/CardPortraits/" 

[update.20.04.tar.gz](https://github.com/borisbabic/hearthstone_hdt_linux/files/6598510/update.20.04.tar.gz)

**Comment by mereong269** [comment]
it is not necessary now.   it fix by HDT.
