### ISSUE TITLE
Install HS with HDT in Wine 7.3 ( 64 bit ) update

### ISSUE THREAD

**Issue by mereong269** [borisbabic/hearthstone_hdt_linux#21]
test environments : Ubuntu 21.10   
                               wine-staging 7.3  wine (64 bit). 
                               wine prefix =  .hs64
                               An error occurs in wine versions higher than 7.3.
                               using hdt.reg.

----------------------------------------------------------------------------------------------------------------------

sudo dpkg --add-architecture i386 

wget -nc https://dl.winehq.org/wine-builds/winehq.key
sudo -H gpg -o /etc/apt/trusted.gpg.d/winehq.key.gpg --dearmor winehq.key
sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ impish main'

sudo apt update

----------------------------------------------------------------------------------------------------------------------

sudo apt -y install --install-recommends wine-staging-i386=7.3\~impish-1
sudo apt -y install --install-recommends wine-staging-amd64=7.3\~impish-1
sudo apt -y install --install-recommends wine-staging=7.3\~impish-1
sudo apt -y install --install-recommends winehq-staging=7.3\~impish-1

sudo apt-mark hold wine-staging-i386
sudo apt-mark hold wine-staging-amd64
sudo apt-mark hold wine-staging
sudo apt-mark hold winehq-staging

----------------------------------------------------------------------------------------------------------------------

sudo apt -y install winetricks

sudo apt clean 
sudo apt update 
sudo apt -y upgrade
sudo apt -y autoremove

----------------------------------------------------------------------------------------------------------------------

env WINEPREFIX="$HOME/.hs64" wineboot --init
-- if Wine prompts for installing Mono, click Cancel.

env WINEPREFIX="$HOME/.hs64" winetricks --force dotnet48 corefonts

env WINEPREFIX="$HOME/.hs64" regedit hdt.reg

env WINEPREFIX="$HOME/.hs64" wine HDT-Installer.exe

env WINEPREFIX="$HOME/.hs64" wine Battle.net-Setup.exe

----------------------------------------------------------------------------------------------------------------------

on Ubuntu 22,04 
=============

1) if you can't finish installation, just click cancel button and then launch battle.net app.

2) replace agent.exe file (C:\ProgramData\Battle.net\Agent\Agent.8009\).

ref :: [https://www.reddit.com/r/Lutris/comments/xgixdk/comment/ioth7qx/](https://www.reddit.com/r/Lutris/comments/xgixdk/comment/ioth7qx/)

**Comment by ayykamp** [comment]
worked for me ty :)

**Comment by Nachh** [comment]
> worked for me ty :)

Hi ! What distribution are you using? On Arch Linux I am not able to run the HDT installer and the --init step also gives me problems.

**Comment by ayykamp** [comment]
Im on Manjaro using Gnome DE. For the dependencies I just ran:

`sudo pacman -S wine-staging winetricks lib32-libldap lib32-gnutls` and then following the steps in this issue ¯\\_(ツ)_/¯

**Comment by mereong269** [comment]
> > worked for me ty :)
> 
> Hi ! What distribution are you using? On Arch Linux I am not able to run the HDT installer and the --init step also gives me problems.

if it is not work,  reference this site.

[https://appdb.winehq.org/objectManager.php?sClass=version&iId=38203&sAllBugs](https://appdb.winehq.org/objectManager.php?sClass=version&iId=38203&sAllBugs)

**Comment by Nachh** [comment]
Hey guys, working flawlessly atm with 7.10 & 7.11 !!

There are two differences in my installation process:

1. ACCEPT when wine prompts to fors intalling Mono.
2. Added d3dcompiler library:  
`env WINEPREFIX="$HOME/.hs64" winetricks --force dotnet48 corefonts d3dcompiler_47`

I have also tried without adding the registry stuff but I am not sure if it has an impact on performance, but it works.

**Tested on a Zenbook with intel integrated graphics and a desktop pc (8700k, 3070ti), both with Arch Linux + xfce.**

PD: I am thinking about how to give visibility to this. I will add a report on winehq, write on reddit and maybe create a repository referencing this and these comments. What do you think? @borisbabic @mereong269 @ayykamp

**Comment by mereong269** [comment]
> Hey guys, working flawlessly atm with 7.10 & 7.11 !!
> 
> There are two differences in my installation process:
> 
> 1. ACCEPT when wine prompts to fors intalling Mono.
> 2. Added d3dcompiler library:
>    `env WINEPREFIX="$HOME/.hs64" winetricks --force dotnet48 corefonts d3dcompiler_47`
> 
> I have also tried without adding the registry stuff but I am not sure if it has an impact on performance, but it works.
> 
> **Tested on a Zenbook with intel integrated graphics and a desktop pc (8700k, 3070ti), both with Arch Linux + xfce.**
> 
> PD: I am thinking about how to give visibility to this. I will add a report on winehq, write on reddit and maybe create a repository referencing this and these comments. What do you think? @borisbabic @mereong269 @ayykamp

it works that your installation process with 7.3.

but it occurs error that visible issue. ( i tested 7.10 , 7.11 and 7.14. ) 

:)
