### ISSUE TITLE
HDT needs .net 4.7 now.

### ISSUE THREAD

**Issue by D33M0N** [borisbabic/hearthstone_hdt_linux#7]
WINEPREFIX=~/wine.hs wine ~/Downloads/HDT-Installer.exe

does give you the option to install it for you, however it does seem to hang at some point @ Downloading netfx_Full_x86.msi ... dunno... will wait. Maybe it will finish at some point.

emm nope. and if you do install dotnet472 with winetricks, then the HDT installer just crashes with new wine-staging 5.7.

**Comment by icetbr** [comment]
The tips provided here worked for me

https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues/4055

**Comment by D33M0N** [comment]
Thank you! Got it sorted now. Downgrade to wine-staging 5.8, avalon.graphics thing added works.
Just for info into your readme, in Xfce with Xfwm4 also only windowed mode works with overlay.
Also I believe you don't need to set the win7 anymore as installing dotnet472 does it for you.

**Comment by borisbabic** [comment]
I forgot to close this, the instructions have been updated.
